#!/bin/bash
set -euo pipefail

sleep 0.2

read -rp "USERNAME: " USERNAME
while true; do
    read -rsp "PASSWD: " PASSWORD
    echo
    read -rsp "CONFIRM PASSWD: " PASSWORD_CONFIRM
    echo
    if [ "$PASSWORD" = "$PASSWORD_CONFIRM" ]; then
        break
    else
        echo "Passwords do not match. Please try again."
    fi
done

#read -rp "REGION: " R
R="Europe/Amsterdam"

HDD="nvme0n1"
DISK="/dev/$HDD"
SIZE1=3
SIZE2=275

PART_UUID=annoying
CRYPTNAME=annoying

reflector -c "NL" -p https --age 4 --latest 15 --save /etc/pacman.d/mirrorlist
sed -i 's/^SigLevel.*/SigLevel = Never/' /etc/pacman.conf
sed -i 's/^LocalFileSigLevel.*/LocalFileSigLevel = Never/' /etc/pacman.conf
sed -i '/^\[options\]/a \
Color' /etc/pacman.conf

cat /etc/pacman.d/mirrorlist

echo
lsblk
echo

echo "ALL DATA ON DISK $DISK WILL BE ERASED!"
echo
echo "GOING TO PARTITION $DISK..."
echo

#read -n 1 -s -r -p "Press a key to continue..."

#while true; do
#    read -n 1 -s -r -p "PROCEED? Type a letter...(Yy/Nn) " answer
#    echo
#    case $answer in
#        [Yy]* ) echo "Continuing..."; break;;
#        [Nn]* ) echo "Aborted."; exit 1;;
#        * ) echo "Please answer y or n.";;
#    esac
#done

echo

#sgdisk -Z $DISK

echo
#read -n 1 -s -r -p "Press a key to continue..."
echo
echo

#sgdisk -n 1::+3G -t 1:EF00 -c 1:"EFI" $DISK
#sgdisk -n 2::+275G -t 2:8300 -c 2:"ROOT" $DISK
#sgdisk -n 3::+4G -t 3:8200 -c 3:"SWAP" $DISK
#sgdisk -n 4:: -t 4:8300 -c 4:"SECONDROOT" $DISK

echo
lsblk
echo
#read -n 1 -s -r -p "Press a key to continue..."
echo
echo

cryptsetup luksFormat ${DISK}p2
cryptsetup open ${DISK}p2 cryptroot

mkfs.fat ${DISK}p1
#cryptsetup luksFormat ${DISK}p1
#cryptsetup open ${DISK}p1 bootcrypt
#mkfs.fat /dev/mapper/bootcrypt

mkfs.xfs /dev/mapper/cryptroot
#mkfs.ext4 /dev/mapper/cryptroot
#mkfs.ext4 -F ${DISK}p4
mkswap ${DISK}p3
swapon ${DISK}p3

mount /dev/mapper/cryptroot /mnt
#mount -m /dev/mapper/bootcrypt /mnt/boot
mount -o umask=0077 -m ${DISK}p1 /mnt/boot

#timedatectl set-timezone $R
#pacman-key --init

pacstrap -K /mnt base

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt bash <<😺
set -e

pacman -S --noconfirm mkinitcpio
sed -i 's/^HOOKS=.*/HOOKS=(base udev autodetect modconf keyboard block encrypt filesystems)/' /etc/mkinitcpio.conf
#!!!! sed -i 's/^HOOKS=.*/HOOKS=(base systemd autodetect keyboard sd-vconsole block sd-encrypt filesystems)/' /etc/mkinitcpio.conf

#!!!                      HOOKS=(base systemd autodetect keyboard sd-vconsole block sd-encrypt filesystems)

sed -i 's/^SigLevel.*/SigLevel = Never/' /etc/pacman.conf
sed -i 's/^LocalFileSigLevel.*/LocalFileSigLevel = Never/' /etc/pacman.conf
sed -i '/^\[options\]/a \
Color' /etc/pacman.conf

curl -LO https://github.com/instantuzer/install/raw/main/pkgs

grep -v '^\s*#' pkgs | pacman -S --needed --noconfirm -

echo "root:$PASSWORD" | chpasswd

useradd -mG wheel $USERNAME
echo "$USERNAME:$PASSWORD" | chpasswd
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

sed -i 's/fmask=0022,dmask=0022/umask=0077/' /etc/fstab

#grub-install --efi-directory=/
#grub-mkconfig -o //grub/grub.cfg

bootctl install
echo "title notebook" >> /boot/loader/entries/arch.conf
echo "linux /vmlinuz-linux-zen" >> /boot/loader/entries/arch.conf
echo "initrd /intel-ucode.img" >> /boot/loader/entries/arch.conf
echo "initrd /initramfs-linux-zen.img" >> /boot/loader/entries/arch.conf
echo "options cryptdevice=${DISK}p2:cryptroot root=/dev/mapper/cryptroot rw" >> /boot/loader/entries/arch.conf
#!!!! echo "options rd.luks.name=${DISK}p2=cryptroot root=/dev/mapper/cryptroot rw" >> /boot/loader/entries/arch.conf
#!@@!! echo "options root=/dev/mapper/cryptroot rw rd.luks.name=${DISK}p2=cryptroot" >> /boot/loader/entries/arch.conf

#!!!! PART_UUID=$(blkid -s UUID -o value "${DISK}p2") 
# Adjust partition number if needed
#!!!! echo "Detected UUID: $PART_UUID"
#!!!! echo "$CRYPTNAME UUID=$PART_UUID none luks" > /etc/crypttab
#####
#!!!! echo "cryptroot UUID=888439a7-cbbb-407e-a543-7bf8813360f0 none luks" >> /etc/crypttab

#!!!! rd.luks.name=UUID=xxxx=cryptroot root=/dev/mapper/cryptroot

echo "[zram0]" >> /etc/systemd/zram-generator.conf
echo "zram-size = ram / 2" >> /etc/systemd/zram-generator.conf
echo "compression-algorithm = zstd" >> /etc/systemd/zram-generator.conf

echo "vm.swappiness=10" >> /etc/sysctl.d/99-swappiness.conf

echo "ACTION=='add|change', KERNEL=='nvme0n1', ATTR{queue/nomerges}='1'" >> /etc/udev/rules.d/99-nvme-nomerge.rules

echo "Section \"InputClass\"" >> /etc/X11/xorg.conf.d/30-touchpad.conf
echo "    Identifier \"touchpad\"" >> /etc/X11/xorg.conf.d/30-touchpad.conf
echo "    MatchIsTouchpad \"on\"" >> /etc/X11/xorg.conf.d/30-touchpad.conf
echo "    Driver \"libinput\"" >> /etc/X11/xorg.conf.d/30-touchpad.conf
echo "    Option \"Tapping\" \"on\"" >> /etc/X11/xorg.conf.d/30-touchpad.conf
echo "EndSection" >> /etc/X11/xorg.conf.d/30-touchpad.conf

echo "Section \"InputClass\"" >> /etc/X11/xorg.conf.d/00-keyboard.conf
echo "    Identifier \"system-keyboard\"" >> /etc/X11/xorg.conf.d/00-keyboard.conf
echo "    MatchIsKeyboard \"on\"" >> /etc/X11/xorg.conf.d/00-keyboard.conf
echo "    Option \"XkbOptions\" \"caps:escape_shifted_capslock\"" >> /etc/X11/xorg.conf.d/00-keyboard.conf
echo "EndSection" >> /etc/X11/xorg.conf.d/00-keyboard.conf

echo "8.8.8.8,1.1.1.1,2001:4860:4860::8888,2606:4700:4700::1111"

systemctl enable NetworkManager

systemctl enable fstrim.timer

echo "notebook" >> /etc/hostname

ln -sf /usr/share/zoneinfo/$R /etc/localtime
hwclock --systohc

su - $USERNAME -c 'mkdir lol && cd lol && git clone https://github.com/instantuzer/install . && stow --no-folding --adopt . && git restore .'

😺

echo
echo
echo "hello world"
echo
echo
