#!/bin/bash
set -euo pipefail

read -rp "USERNAME: " USERNAME
while true; do
    read -rsp "PASSWD: " PASSWORD
    echo
    read -rsp "CONFIRM PASSWD: " PASSWORD_CONFIRM
    echo
    if [ "$PASSWORD" = "$PASSWORD_CONFIRM" ]; then
        break
    else
        echo "Passwords do not match. Please try again."
    fi
done

#read -rp "REGION: " R
R="Europe/Amsterdam"

HDD="nvme0n1"
DISK="/dev/$HDD"
SIZE1=3
SIZE2=275

reflector -c "nl" -p https --age 4 --latest 15 --save /etc/pacman.d/mirrorlist
sed -i 's/^ParallelDownloads.*/ParallelDownloads = 15/' /etc/pacman.conf
sed -i '/^\[options\]/a \
Color' /etc/pacman.conf

cat /etc/pacman.d/mirrorlist
echo
lsblk
echo

echo "---->>> Installing to $DISK"
echo "ALL DATA ON THIS DISK WILL BE ERASED!"
echo "Partitioning $DISK..."
#read -n 1 -s -r -p "Press a key to continue..."
while true; do
    read -n 1 -s -r -p "Do you want to proceed? (y/n) " answer
    echo
    case $answer in
        [Yy]* ) echo "Continuing..."; break;;
        [Nn]* ) echo "Aborted."; exit 1;;
        * ) echo "Please answer y or n.";;
    esac
done

#sgdisk -Z $DISK
#sgdisk -n 1::+3G -t 1:EF00 -c 1:"EFI" $DISK
#sgdisk -n 2::+275G -t 2:8300 -c 2:"ROOT" $DISK
#sgdisk -n 3::+8G -t 3:8200 -c 3:"SWAP" $DISK
#sgdisk -n 4:: -t 4:8300 -c 4:"SECONDROOT" $DISK

lsblk
echo
read -n 1 -s -r -p "Press a key to continue..."
echo

mkfs.fat ${DISK}p1
mkfs.ext4 -F ${DISK}p2
mkfs.ext4 ${DISK}p4
mkswap ${DISK}p3
swapon ${DISK}p3

mount ${DISK}p2 /mnt
mount -m ${DISK}p1 /mnt/boot

timedatectl set-timezone $R

pacstrap /mnt base linux linux-zen linux-firmware-intel intel-ucode

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt bash <<😺
set -e

sed -i 's/^ParallelDownloads.*/ParallelDownloads = 15/' /etc/pacman.conf
sed -i '/^\[options\]/a \
Color' /etc/pacman.conf

curl -LO https://github.com/instantuzer/install/raw/main/pkgs

pacman -S --needed --noconfirm - < pkgs

echo "root:$PASSWORD" | chpasswd

useradd -mG wheel $USERNAME
echo "$USERNAME:$PASSWORD" | chpasswd
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

#grub-install --efi-directory=/boot
#grub-mkconfig -o /boot/grub/grub.cfg

bootctl install
echo "title terminat0r" >> /boot/loader/entries/arch.conf
echo "linux /vmlinuz-linux-zen" >> /boot/loader/entries/arch.conf
echo "initrd /intel-ucode.img" >> /boot/loader/entries/arch.conf
echo "initrd /initramfs-linux-zen.img" >> /boot/loader/entries/arch.conf
echo "options root=/dev/nvme0n1p2 rw" >> /boot/loader/entries/arch.conf

systemctl enable NetworkManager
systemctl enable fstrim.timer
echo "terminat0r" >> /etc/hostname
ln -sf /usr/share/zoneinfo/$R /etc/localtime
hwclock --systohc

su - $USERNAME -c 'mkdir lol && cd lol && git clone https://github.com/instantuzer/install . && stow --no-folding --adopt . && git restore .'

😺
