#!/bin/bash
set -euo pipefail

read -rp "USERNAME: " USERNAME
while true; do
    read -rsp "PASSWD: " PASSWORD
    echo
    read -rsp "CONFIRM PASSWD: " PASSWORD_CONFIRM
    echo
    if [ "$PASSWORD" = "$PASSWORD_CONFIRM" ]; then
        break
    else
        echo "Passwords do not match. Please try again."
    fi
done

#read -rp "REGION: " R
R="Europe/Amsterdam"

HDD="sda"
DISK="/dev/$HDD"
SIZE1=3
SIZE2=275

reflector -c "nl" -p https --age 4 --latest 15 --save /etc/pacman.d/mirrorlist
sed -i 's/^SigLevel.*/SigLevel = Never/' /etc/pacman.conf
sed -i 's/^LocalFileSigLevel.*/LocalFileSigLevel = Never/' /etc/pacman.conf
sed -i '/^\[options\]/a \
Color' /etc/pacman.conf

cat /etc/pacman.d/mirrorlist

echo
lsblk
echo

echo "ALL DATA ON DISK $DISK WILL BE ERASED!"
echo
echo "GOING TO PARTITION $DISK..."
echo

#read -n 1 -s -r -p "Press a key to continue..."

while true; do
    read -n 1 -s -r -p "PROCEED? Type a letter...(Yy/Nn) " answer
    echo
    case $answer in
        [Yy]* ) echo "Continuing..."; break;;
        [Nn]* ) echo "Aborted."; exit 1;;
        * ) echo "Please answer y or n.";;
    esac
done

echo

sgdisk -Z $DISK

echo
read -n 1 -s -r -p "Press a key to continue..."
echo
echo

sgdisk -n 1::+3G -t 1:EF00 -c 1:"EFI" $DISK
sgdisk -n 2::+275G -t 2:8300 -c 2:"ROOT" $DISK
sgdisk -n 3::+4G -t 3:8200 -c 3:"SWAP" $DISK

echo
lsblk
echo
read -n 1 -s -r -p "Press a key to continue..."
echo
echo

cryptsetup luksFormat ${DISK}2
cryptsetup open ${DISK}2 cryptroot

mkfs.fat ${DISK}1
mkfs.ext4 /dev/mapper/cryptroot
#mkfs.ext4 -F ${DISK}p4
mkswap ${DISK}3
swapon ${DISK}3

mount /dev/mapper/cryptroot /mnt
mount -m ${DISK}1 /mnt/boot

#timedatectl set-timezone $R
#pacman-key --init

pacstrap -K /mnt base

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt bash <<😺
set -e

pacman -S --noconfirm mkinitcpio
sed -i 's/^HOOKS=.*/HOOKS=(base udev autodetect modconf keyboard block encrypt filesystems fsck)/' /etc/mkinitcpio.conf

sed -i 's/^SigLevel.*/SigLevel = Never/' /etc/pacman.conf
sed -i 's/^LocalFileSigLevel.*/LocalFileSigLevel = Never/' /etc/pacman.conf
sed -i '/^\[options\]/a \
Color' /etc/pacman.conf

curl -LO https://github.com/instantuzer/install/raw/main/pkgs

grep -v '^\s*#' pkgs | pacman -S --needed --noconfirm -

echo "root:$PASSWORD" | chpasswd

useradd -mG wheel $USERNAME
echo "$USERNAME:$PASSWORD" | chpasswd
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

#grub-install --efi-directory=/
#grub-mkconfig -o //grub/grub.cfg

bootctl install
echo "title TV" >> /boot/loader/entries/arch.conf
echo "linux /vmlinuz-linux-zen" >> /boot/loader/entries/arch.conf
echo "initrd /intel-ucode.img" >> /boot/loader/entries/arch.conf
echo "initrd /initramfs-linux-zen.img" >> /boot/loader/entries/arch.conf
echo "options cryptdevice=${DISK}2:T-1000 root=/dev/mapper/T-1000 rw i915.enable_psr=1 i915.enable_fbc=1" >> /boot/loader/entries/arch.conf

echo "8.8.8.8,1.1.1.1,2001:4860:4860::8888,2606:4700:4700::1111"

systemctl enable NetworkManager

systemctl enable fstrim.timer

echo "TV" >> /etc/hostname

ln -sf /usr/share/zoneinfo/$R /etc/localtime
hwclock --systohc

su - $USERNAME -c 'mkdir lol && cd lol && git clone https://github.com/instantuzer/install . && stow --no-folding --adopt . && git restore .'

😺

echo
echo
echo "hello world"
echo
echo
