#!/bin/bash
set -euo pipefail

read -rp "COUNTRY: " CNTRY
reflector -c "$CNTRY" -p https --age 4 --latest 15 --save /etc/pacman.d/mirrorlist
cat /etc/pacman.d/mirrorlist

echo

lsblk

echo

read -rp "HDD: " HDD
read -rp "EFISIZE: " SIZE1
read -rp "ROOTSIZE: " SIZE2

read -rp "USERNAME: " USERNAME

while true; do
    read -rsp "PASSWD: " PASSWORD
    echo
    read -rsp "CONFIRM PASSWD: " PASSWORD_CONFIRM
    echo
    if [ "$PASSWORD" == "$PASSWORD_CONFIRM" ]; then
        break
    else
        echo "Passwords do not match. Please try again."
    fi
done

read -rp "REGION: " R
read -rp "CITY: " C

DISK="/dev/$HDD"
echo "---->>> Installing to $DISK"
echo "ALL DATA ON THIS DISK WILL BE ERASED!"
read -rp "ARE YOU SURE? (y/n): " CONFIRM
if [ "$CONFIRM" != "y" ]; then
    echo "Installation aborted."
    exit 1
fi

echo "Partitioning $DISK..."
sgdisk -Z $DISK
sgdisk -n 1::+${SIZE1}G -t 1:EF00 -c 1:"EFI" $DISK
sgdisk -n 2::+${SIZE2}G -t 2:8300 -c 2:"ROOT" $DISK

lsblk

read -rp "EXT:" EXT

mkfs.fat ${DISK}${EXT}1
mkfs.ext4 -F ${DISK}${EXT}2

mount ${DISK}${EXT}2 /mnt
mount -m ${DISK}${EXT}1 /mnt/boot

pacstrap /mnt base linux linux-firmware-intel linux-zen intel-ucode

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt bash <<😺
set -e

curl -LO https://github.com/instantuzer/install/raw/main/pkgs

pacman -Sy --needed --noconfirm - < pkgs

echo "root:$PASSWORD" | chpasswd

useradd -mG wheel $USERNAME
echo "$USERNAME:$PASSWORD" | chpasswd
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

grub-install --efi-directory=/boot
grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable NetworkManager
echo "lol" >> /etc/hostname
ln -sf /usr/share/zoneinfo/$R/$C /etc/localtime
hwclock --systohc

su - $USERNAME -c 'mkdir lol && cd lol && git clone https://github.com/instantuzer/install . && stow --no-folding --adopt . && git restore .'

😺
