#!/bin/bash
set -euo pipefail

reflector -c "nl" -p https --age 4 --latest 15 --save /etc/pacman.d/mirrorlist
cat /etc/pacman.d/mirrorlist

echo

lsblk

echo

HDD=nvme0n1
SIZE1=3
SIZE2=275

read -rp "USERNAME: " USERNAME

while true; do
    read -rsp "PASSWD: " PASSWORD
    echo
    read -rsp "CONFIRM PASSWD: " PASSWORD_CONFIRM
    echo
    if [ "$PASSWORD" == "$PASSWORD_CONFIRM" ]; then
        break
    else
        echo "Passwords do not match. Please try again."
    fi
done

read -rp "REGION: " R

DISK="/dev/$HDD"

echo "---->>> Installing to $DISK"
echo "ALL DATA ON THIS DISK WILL BE ERASED!"
echo "Partitioning $DISK..."

sgdisk -Z $DISK
sgdisk -n 1::+3G -t 1:EF00 -c 1:"EFI" $DISK
sgdisk -n 2::+275G -t 2:8300 -c 2:"ROOT" $DISK

mkfs.fat ${DISK}p1
mkfs.ext4 -F ${DISK}p2

mount ${DISK}p2 /mnt
mount -m ${DISK}p1 /mnt/boot

pacstrap /mnt base linux linux-firmware-intel linux-zen intel-ucode

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt bash <<😺
set -e

curl -LO https://github.com/instantuzer/install/raw/main/pkgs

pacman -Sy --needed --noconfirm - < pkgs

echo "root:$PASSWORD" | chpasswd

useradd -mG wheel $USERNAME
echo "$USERNAME:$PASSWORD" | chpasswd
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

#grub-install --efi-directory=/boot
#grub-mkconfig -o /boot/grub/grub.cfg

bootctl install
echo "title lol" >> /boot/loader/entries/arch.conf
echo "linux /vmlinuz-linux" >> /boot/loader/entries/arch.conf
echo "initrd /initramfs-linux.img" >> /boot/loader/entries/arch.conf
echo "options root=/dev/nvme0n1p2 rw" >> /boot/loader/entries/arch.conf

systemctl enable NetworkManager
systemctl enable fstrim.timer
echo "lol" >> /etc/hostname
ln -sf /usr/share/zoneinfo/$R /etc/localtime
hwclock --systohc

su - $USERNAME -c 'mkdir lol && cd lol && git clone https://github.com/instantuzer/install . && stow --no-folding --adopt . && git restore .'

😺
