#!/bin/bash

DNS4="8.8.8.8 1.1.1.1"
DNS6="2001:4860:4860::8888 2606:4700:4700::1111"

for CONN in $(nmcli -t -f NAME connection show --active); do

	if [[ "$CONN" == "lo" ]]; then
        continue
    fi

    nmcli connection modify "$CONN" \
    ipv4.ignore-auto-dns yes \
    ipv4.dns "$DNS4" \
    ipv6.ignore-auto-dns yes \
    ipv6.dns "$DNS6"
done

nmcli connection up "$CONN"
